### PR TITLE
ci: add feature branch actions

### PR DESCRIPTION
**Pull request by dnnnvx**

### CODE REVIEW

**Review by chybisov — COMMENTED** [review]
Can we please change `packages/widget-embedded/dist` to `packages/widget-playground/dist` 🙂

**Comment by dnnnvx** [comment]
> Can we please change `packages/widget-embedded/dist` to `packages/widget-playground/dist` 🙂

Ah I was creating the action for both 👀 should be only playground?

**Comment by chybisov** [comment]
@dnnnvx Yep, `widget-playground` should be enough for now 🙂

**Review by chybisov — APPROVED** [review]
Works like a charm 🙂

**Pull request merged**
